use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::path::Path;

/// A resolved package lockfile (`vsync.lock`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Lockfile {
    #[serde(rename = "lockfile-version")]
    pub lockfile_version: u32,

    #[serde(default)]
    pub packages: Vec<LockedPackage>,
}

/// A single locked package entry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub realm: String,
    pub checksum: String,
    pub source: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
}

impl Lockfile {
    /// Create a new empty lockfile with version 1.
    pub fn new() -> Self {
        Self {
            lockfile_version: 1,
            packages: Vec::new(),
        }
    }

    /// Parse a lockfile from its TOML string representation.
    pub fn parse(content: &str) -> Result<Self> {
        let parsed: Lockfile =
            toml::from_str(content).context("failed to parse vsync.lock")?;
        if parsed.lockfile_version > 1 {
            bail!(
                "vsync.lock has lockfile-version {}, which requires a newer version of vsync. \
                 Please upgrade vsync.",
                parsed.lockfile_version
            );
        }
        Ok(parsed)
    }

    /// Load a lockfile from the given path, returning `None` if the file does not exist.
    pub fn load(path: &Path) -> Result<Option<Self>> {
        if !path.exists() {
            return Ok(None);
        }
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        Self::parse(&content).map(Some)
    }

    /// Write the lockfile to disk atomically via temp file + rename.
    pub fn save(&self, path: &Path) -> Result<()> {
        let content = self.to_string();
        let tmp = path.with_extension("lock.tmp");
        std::fs::write(&tmp, content.as_bytes())
            .with_context(|| format!("failed to write {}", tmp.display()))?;
        std::fs::rename(&tmp, path)
            .with_context(|| format!("failed to rename {} to {}", tmp.display(), path.display()))
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for Lockfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "# This file is auto-generated by vsync. Do not edit.")?;
        writeln!(f, "# To update, run `vsync install` or `vsync update`.")?;
        writeln!(f)?;
        let serialized = toml::to_string_pretty(self).map_err(|_| fmt::Error)?;
        write!(f, "{serialized}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lockfile_roundtrip() {
        let mut lf = Lockfile::new();
        lf.packages.push(LockedPackage {
            name: "roblox/roact".to_string(),
            version: "17.0.1".to_string(),
            realm: "shared".to_string(),
            checksum: "abc123".to_string(),
            source: "wally".to_string(),
            dependencies: vec!["roblox/react-lua@0.1.0".to_string()],
        });

        let text = lf.to_string();
        let parsed = Lockfile::parse(&text).expect("roundtrip parse");
        assert_eq!(lf, parsed);
    }

    #[test]
    fn lockfile_rejects_future_version() {
        let toml = r#"
lockfile-version = 99

[[packages]]
name = "x/y"
version = "1.0.0"
realm = "shared"
checksum = "abc"
source = "wally"
"#;
        let err = Lockfile::parse(toml).unwrap_err();
        let msg = format!("{err}");
        assert!(
            msg.contains("upgrade vsync"),
            "expected 'upgrade vsync' in error, got: {msg}"
        );
    }
}
